services:

  markocupic.dummy_bundle.controller.fontend_module.dummy_module_controller:
    class: Markocupic\DummyBundle\Controller\FrontendModule\DummyModuleController
    arguments:
      - '@contao.framework'
      - '@database_connection'
      - '%kernel.project_dir%'
      - '@security.helper'
      - '@request_stack'
      - '@contao.routing.scope_matcher'
    tags:
      - { name: contao.frontend_module, category: miscellaneous }
    public: true

